version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres
    restart: 'always'
    environment:
      POSTGRES_PASSWORD: newPass123
      POSTGRES_USER: pastauser
      POSTGRES_DB: pastadb
    volumes:
      - '~/pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  backend:
    image: pasta-image
    container_name: backend
    restart: 'always'
    depends_on:
      - db
    environment:
      DB_NAME: pastadb
      DB_USERNAME: pastauser
      DB_PASSWORD: newPass123
      DB_HOST: postgres
      JWT_SECRET: superpupersecret
    ports:
      - '3000:3000'
